const colors = require("tailwindcss/colors");
module.exports = {
    content: ["./src/**/*.{html,js}"],
    darkMode: "class",
    theme: {
        extend: {},
        colors: {
            ...colors,
            purple: "#6A197D",
            yellow: "#F3BA2F",
            transparent: "#0000",
            current: "currentColor",
            walletIndigo: "#2F2E4F",
            mainIndigo: "#26283E",
            sideIndigo: "#2C2B4A",
            itemPurple: "#B961FF",
            itemIndigo: "#6E00FF",
            mainWhite: "#F0F2F9",
            linkBlue: "#304AFF",
            mainOrange: "#FF4C0A",
            buttonDarkOrange: "#FF7A49",
            buttonLightOrange: "#FF9670",
            inputBg: "#CED4FF",
            cardDarkBg: "#323157",
            itemCyan: "#26e0ff",
            intenseBg: "#160040",
            intenseOrange: "#FF6E38",
            comment: "#6F6C90",
            blueGrSt: "#0ACFFE",
            blueGrEd: "#495AFF",
            darkBlue: "#2752E7",
            darkGray: "#2C3131",
        },
    },
    plugins: [],
};
